In [ ]:
# %pip install openpyxl ( install if any error occur on excel file)
# HAve the required data file in CSV or Excell

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
df = pd.read_excel(r'C:\Users\patharapilli\OneDrive - adesso Group\Documents\Mohan.P\learnings\NarashIT\JunBatch\21st_Jul_Pandas\data.xlsx')

In [4]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [5]:
len(df)

195

In [6]:
df.shape

(195, 5)

In [7]:
x = df.iloc[:,:-1]
y = df.iloc[:,4]

In [9]:
x

              CountryName CountryCode  BirthRate  InternetUsers
0                   Aruba         ABW     10.244           78.9
1             Afghanistan         AFG     35.253            5.9
2                  Angola         AGO     45.985           19.1
3                 Albania         ALB     12.877           57.2
4    United Arab Emirates         ARE     11.044           88.0
..                    ...         ...        ...            ...
190           Yemen, Rep.         YEM     32.947           20.0
191          South Africa         ZAF     20.850           46.5
192      Congo, Dem. Rep.         COD     42.394            2.2
193                Zambia         ZMB     40.471           15.4
194              Zimbabwe         ZWE     35.715           18.5

[195 rows x 4 columns]

In [8]:
y

0              High income
1               Low income
2      Upper middle income
3      Upper middle income
4              High income
              ...
190    Lower middle income
191    Upper middle income
192             Low income
193    Lower middle income
194             Low income
Name: IncomeGroup, Length: 195, dtype: object

In [9]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [10]:
len(df.columns)

5

In [11]:
df.isnull()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [12]:
df.isnull()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [16]:
df.isna()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [13]:
df.isna().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [14]:
type(df)

pandas.core.frame.DataFrame

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [20]:
df.shape

(195, 5)

In [21]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [22]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df.head()  # print top 5 rows (0 to 4 rows)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [18]:
df.head(20) # gives the data from 0 to 19 records

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.90000,High income
1,Afghanistan,AFG,35.253,5.90000,Low income
2,Angola,AGO,45.985,19.10000,Upper middle income
3,Albania,ALB,12.877,57.20000,Upper middle income
4,United Arab Emirates,ARE,11.044,88.00000,High income
5,Argentina,ARG,17.716,59.90000,High income
6,Armenia,ARM,13.308,41.90000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.40000,High income
8,Australia,AUS,13.200,83.00000,High income
9,Austria,AUT,9.400,80.61880,High income
10,Azerbaijan,AZE,18.300,58.70000,Upper middle income
11,Burundi,BDI,44.151,1.30000,Low income
12,Belgium,BEL,11.200,82.17020,High income
13,Benin,BEN,36.440,4.90000,Low income
14,Burkina Faso,BFA,40.551,9.10000,Low income
15,Bangladesh,BGD,20.142,6.63000,Lower middle income
16,Bulgaria,BGR,9.200,53.06150,Upper middle income
17,Bahrain,BHR,15.040,90.00004,High income
18,"Bahamas, The",BHS,15.339,72.00000,High income
19,Bosnia and Herzegovina,BIH,9.062,57.79000,Upper middle income

In [20]:
df.tail() # gives the last 5 records

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

# Second day class on Pandas advance (22/07/2026)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [23]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [24]:
df[:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [27]:
df[:10] # it gives data form, ie starts from 0 record to (n-1) ie (10-1)=9 records

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9000,High income
1,Afghanistan,AFG,35.253,5.9000,Low income
2,Angola,AGO,45.985,19.1000,Upper middle income
3,Albania,ALB,12.877,57.2000,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0000,High income
5,Argentina,ARG,17.716,59.9000,High income
6,Armenia,ARM,13.308,41.9000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4000,High income
8,Australia,AUS,13.200,83.0000,High income
9,Austria,AUT,9.400,80.6188,High income

In [28]:
df[10:20] # it will give records from 10 till 20th one (20-1) 19th recored

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
10,Azerbaijan,AZE,18.300,58.70000,Upper middle income
11,Burundi,BDI,44.151,1.30000,Low income
12,Belgium,BEL,11.200,82.17020,High income
13,Benin,BEN,36.440,4.90000,Low income
14,Burkina Faso,BFA,40.551,9.10000,Low income
15,Bangladesh,BGD,20.142,6.63000,Lower middle income
16,Bulgaria,BGR,9.200,53.06150,Upper middle income
17,Bahrain,BHR,15.040,90.00004,High income
18,"Bahamas, The",BHS,15.339,72.00000,High income
19,Bosnia and Herzegovina,BIH,9.062,57.79000,Upper middle income

In [29]:
df[::10] # it gives record of every 10th place

     CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0          Aruba         ABW     10.244      78.900000          High income
10    Azerbaijan         AZE     18.300      58.700000  Upper middle income
20       Belarus         BLR     12.500      54.170000  Upper middle income
30        Canada         CAN     10.900      85.800000          High income
40    Costa Rica         CRI     15.022      45.960000  Upper middle income
50       Ecuador         ECU     21.070      40.353684  Upper middle income
60         Gabon         GAB     30.555       9.200000  Upper middle income
70     Greenland         GRL     14.500      65.800000          High income
80         India         IND     20.291      15.100000  Lower middle income
90    Kazakhstan         KAZ     22.730      54.000000  Upper middle income
100        Libya         LBY     21.425      16.500000  Upper middle income
110      Moldova         MDA     12.141      45.000000  Lower middle income
120   Mozambique         MOZ     39.705       5.400000           Low income
130  Netherlands         NLD     10.200      93.956400          High income
140       Poland         POL      9.600      62.849200          High income
150        Sudan         SDN     33.477      22.700000  Lower middle income
160     Suriname         SUR     18.455      37.400000  Upper middle income
170   Tajikistan         TJK     30.792      16.000000  Lower middle income
180      Uruguay         URY     14.374      57.690000          High income
190  Yemen, Rep.         YEM     32.947      20.000000  Lower middle income

In [30]:
df.info

<bound method DataFrame.info of               CountryName CountryCode  BirthRate  InternetUsers  \
0                   Aruba         ABW     10.244           78.9
1             Afghanistan         AFG     35.253            5.9
2                  Angola         AGO     45.985           19.1
3                 Albania         ALB     12.877           57.2
4    United Arab Emirates         ARE     11.044           88.0
..                    ...         ...        ...            ...
190           Yemen, Rep.         YEM     32.947           20.0
191          South Africa         ZAF     20.850           46.5
192      Congo, Dem. Rep.         COD     42.394            2.2
193                Zambia         ZMB     40.471           15.4
194              Zimbabwe         ZWE     35.715           18.5

             IncomeGroup
0            High income
1             Low income
2    Upper middle income
3    Upper middle income
4            High income
..                   ...
190  Lower middle income
191  Upper middle income
192           Low income
193  Lower middle income
194           Low income

[195 rows x 5 columns]>

In [31]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [32]:
df['BirthRate']

0      10.244
1      35.253
2      45.985
3      12.877
4      11.044
        ...
190    32.947
191    20.850
192    42.394
193    40.471
194    35.715
Name: BirthRate, Length: 195, dtype: float64

In [38]:
df[['BirthRate','InternetUsers']]

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

# Pandas Brackets: When to Use Which One?
    Pandas uses normal Python syntax. The main symbols you will use are:
    Symbol	Common purpose
    ()	     Call a function or method; pass arguments
    []	     Select data, index data, or slice data
    :	     Specify a range/slice inside []
    {}	     Create dictionaries or sets
    .	     Access a method or attribute

In [40]:
df.sort_values('BirthRate')

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
142,Portugal,PRT,7.900,62.0956,High income
74,"Hong Kong SAR, China",HKG,7.900,74.2000,High income
89,Japan,JPN,8.200,89.7100,High income
68,Greece,GRC,8.500,59.8663,High income
45,Germany,DEU,8.500,84.1700,High income
...,...,...,...,...,...
115,Mali,MLI,44.138,3.5000,Low income
11,Burundi,BDI,44.151,1.3000,Low income
167,Chad,TCD,45.745,2.3000,Low income
2,Angola,AGO,45.985,19.1000,Upper middle income
127,Niger,NER,49.661,1.7000,Low income

In [41]:
df.head

<bound method NDFrame.head of               CountryName CountryCode  BirthRate  InternetUsers  \
0                   Aruba         ABW     10.244           78.9
1             Afghanistan         AFG     35.253            5.9
2                  Angola         AGO     45.985           19.1
3                 Albania         ALB     12.877           57.2
4    United Arab Emirates         ARE     11.044           88.0
..                    ...         ...        ...            ...
190           Yemen, Rep.         YEM     32.947           20.0
191          South Africa         ZAF     20.850           46.5
192      Congo, Dem. Rep.         COD     42.394            2.2
193                Zambia         ZMB     40.471           15.4
194              Zimbabwe         ZWE     35.715           18.5

             IncomeGroup
0            High income
1             Low income
2    Upper middle income
3    Upper middle income
4            High income
..                   ...
190  Lower middle income
191  Upper middle income
192           Low income
193  Lower middle income
194           Low income

[195 rows x 5 columns]>

In [43]:
df.head[3]  # Note df.head() is method and we need to use() brackets and not []

TypeError: 'method' object is not subscriptable

In [44]:
df.head(3) # Note head() method takes argument in it as 3 here and give the 3 records. from 0 to 2

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Aruba         ABW     10.244           78.9          High income
1  Afghanistan         AFG     35.253            5.9           Low income
2       Angola         AGO     45.985           19.1  Upper middle income

In [49]:
df['BirthRate'] # it give the recordd of BirthRate. only one column data we can use df[]

0      10.244
1      35.253
2      45.985
3      12.877
4      11.044
        ...
190    32.947
191    20.850
192    42.394
193    40.471
194    35.715
Name: BirthRate, Length: 195, dtype: float64

In [46]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [48]:
df[['BirthRate', 'InternetUsers']] # if we want multiple columns df[[1,2]]
                                        #The outer [] selects data from the DataFrame.
                                        #The inner [] creates a Python list of column names.

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

# split the dataset into numerical dataframes & categorical dataframe

In [50]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [53]:
df_num = df[['BirthRate', 'InternetUsers']]
df_num

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

In [54]:
df_cat = df[['CountryName', 'CountryCode','IncomeGroup']]
df_cat

              CountryName CountryCode          IncomeGroup
0                   Aruba         ABW          High income
1             Afghanistan         AFG           Low income
2                  Angola         AGO  Upper middle income
3                 Albania         ALB  Upper middle income
4    United Arab Emirates         ARE          High income
..                    ...         ...                  ...
190           Yemen, Rep.         YEM  Lower middle income
191          South Africa         ZAF  Upper middle income
192      Congo, Dem. Rep.         COD           Low income
193                Zambia         ZMB  Lower middle income
194              Zimbabwe         ZWE           Low income

[195 rows x 3 columns]

In [55]:
df_num , df_cat

(     BirthRate  InternetUsers
 0       10.244           78.9
 1       35.253            5.9
 2       45.985           19.1
 3       12.877           57.2
 4       11.044           88.0
 ..         ...            ...
 190     32.947           20.0
 191     20.850           46.5
 192     42.394            2.2
 193     40.471           15.4
 194     35.715           18.5

 [195 rows x 2 columns],
               CountryName CountryCode          IncomeGroup
 0                   Aruba         ABW          High income
 1             Afghanistan         AFG           Low income
 2                  Angola         AGO  Upper middle income
 3                 Albania         ALB  Upper middle income
 4    United Arab Emirates         ARE          High income
 ..                    ...         ...                  ...
 190           Yemen, Rep.         YEM  Lower middle income
 191          South Africa         ZAF  Upper middle income
 192      Congo, Dem. Rep.         COD           Low income
 193                Zambia         ZMB  Lower middle income
 194              Zimbabwe         ZWE           Low income

 [195 rows x 3 columns])

In [56]:
df_num.head(2)

   BirthRate  InternetUsers
0     10.244           78.9
1     35.253            5.9

In [57]:
df_cat.head(2)

   CountryName CountryCode  IncomeGroup
0        Aruba         ABW  High income
1  Afghanistan         AFG   Low income

In [58]:
print(df_num.columns)
print(df_cat.columns)

Index(['BirthRate', 'InternetUsers'], dtype='object')
Index(['CountryName', 'CountryCode', 'IncomeGroup'], dtype='object')

In [61]:
print(df_num.isna().sum())
print(df_cat.isna().sum())

BirthRate        0
InternetUsers    0
dtype: int64
CountryName    0
CountryCode    0
IncomeGroup    0
dtype: int64

In [62]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [63]:
df_num.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [64]:
df_cat

              CountryName CountryCode          IncomeGroup
0                   Aruba         ABW          High income
1             Afghanistan         AFG           Low income
2                  Angola         AGO  Upper middle income
3                 Albania         ALB  Upper middle income
4    United Arab Emirates         ARE          High income
..                    ...         ...                  ...
190           Yemen, Rep.         YEM  Lower middle income
191          South Africa         ZAF  Upper middle income
192      Congo, Dem. Rep.         COD           Low income
193                Zambia         ZMB  Lower middle income
194              Zimbabwe         ZWE           Low income

[195 rows x 3 columns]

In [65]:
df_cat.describe()

       CountryName CountryCode  IncomeGroup
count          195         195          195
unique         195         195            4
top          Aruba         ABW  High income
freq             1           1           67

# how to change the column names

In [66]:
df.columns = ['a','b','c','d','e']

In [67]:
df.head(2)

             a    b       c     d            e
0        Aruba  ABW  10.244  78.9  High income
1  Afghanistan  AFG  35.253   5.9   Low income

# Change back to original coulmns

In [68]:
df.columns = ['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers', 'IncomeGroup']

In [69]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0        Aruba         ABW     10.244           78.9  High income
1  Afghanistan         AFG     35.253            5.9   Low income

In [70]:
df.BirthRate * df.InternetUsers

0      808.2516
1      207.9927
2      878.3135
3      736.5644
4      971.8720
         ...
190    658.9400
191    969.5250
192     93.2668
193    623.2534
194    660.7275
Length: 195, dtype: float64

In [71]:
df['myCalc'] = df.BirthRate * df.InternetUsers

In [72]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,myCalc
0,Aruba,ABW,10.244,78.9,High income,808.2516
1,Afghanistan,AFG,35.253,5.9,Low income,207.9927
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135
3,Albania,ALB,12.877,57.2,Upper middle income,736.5644
4,United Arab Emirates,ARE,11.044,88.0,High income,971.8720
...,...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income,658.9400
191,South Africa,ZAF,20.850,46.5,Upper middle income,969.5250
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income,93.2668
193,Zambia,ZMB,40.471,15.4,Lower middle income,623.2534
194,Zimbabwe,ZWE,35.715,18.5,Low income,660.7275

In [73]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup', 'myCalc'],
      dtype='object')

In [74]:
id(df)

1375837385264

In [75]:
df =df.drop('myCalc')

KeyError: "['myCalc'] not found in axis"

In [76]:
df =df.drop('myCalc', axis = 1)

In [77]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

# Filter in dataframe

In [78]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [80]:
df['InternetUsers'] <20

0      False
1       True
2       True
3      False
4      False
       ...
190    False
191    False
192     True
193     True
194     True
Name: InternetUsers, Length: 195, dtype: bool

In [81]:
df[df['InternetUsers'] <20]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
11,Burundi,BDI,44.151,1.3,Low income
13,Benin,BEN,36.440,4.9,Low income
14,Burkina Faso,BFA,40.551,9.1,Low income
...,...,...,...,...,...
187,Vanuatu,VUT,26.739,11.3,Lower middle income
189,Samoa,WSM,26.172,15.3,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [85]:
# df[df['InternetUsers'] <20 & df['BirthRate'] >30]
df[(df.InternetUsers <3 ) & (df.BirthRate >40)]

          CountryName CountryCode  BirthRate  InternetUsers IncomeGroup
11            Burundi         BDI     44.151            1.3  Low income
127             Niger         NER     49.661            1.7  Low income
156           Somalia         SOM     43.891            1.5  Low income
167              Chad         TCD     45.745            2.3  Low income
192  Congo, Dem. Rep.         COD     42.394            2.2  Low income

In [86]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [87]:
df[df.IncomeGroup == 'Lower middle income']

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
6,Armenia,ARM,13.308,41.9000,Lower middle income
15,Bangladesh,BGD,20.142,6.6300,Lower middle income
23,Bolivia,BOL,24.236,36.9400,Lower middle income
27,Bhutan,BTN,18.134,29.9000,Lower middle income
34,Cote d'Ivoire,CIV,37.320,8.4000,Lower middle income
35,Cameroon,CMR,37.236,6.4000,Lower middle income
36,"Congo, Rep.",COG,37.011,6.6000,Lower middle income
39,Cabo Verde,CPV,21.625,37.5000,Lower middle income
46,Djibouti,DJI,25.486,9.5000,Lower middle income
51,"Egypt, Arab Rep.",EGY,28.032,29.4000,Lower middle income
59,"Micronesia, Fed. Sts.",FSM,23.511,27.8000,Lower middle income
62,Georgia,GEO,13.332,43.3000,Lower middle income
63,Ghana,GHA,33.131,12.3000,Lower middle income
71,Guatemala,GTM,27.465,19.7000,Lower middle income
73,Guyana,GUY,18.885,35.0000,Lower middle income
75,Honduras,HND,21.593,17.8000,Lower middle income
79,Indonesia,IDN,20.297,14.9400,Lower middle income
80,India,IND,20.291,15.1000,Lower middle income
91,Kenya,KEN,35.194,39.0000,Lower middle income
92,Kyrgyz Republic,KGZ,27.200,23.0000,Lower middle income
94,Kiribati,KIR,29.044,11.5000,Lower middle income
97,Lao PDR,LAO,27.051,12.5000,Lower middle income
103,Sri Lanka,LKA,17.863,21.9000,Lower middle income
104,Lesotho,LSO,28.738,5.0000,Lower middle income
109,Morocco,MAR,21.023,56.0000,Lower middle income
110,Moldova,MDA,12.141,45.0000,Lower middle income
117,Myanmar,MMR,18.119,1.6000,Lower middle income
121,Mauritania,MRT,33.801,6.2000,Lower middle income
128,Nigeria,NGA,40.045,38.0000,Lower middle income
129,Nicaragua,NIC,20.788,15.5000,Lower middle income
135,Pakistan,PAK,29.582,10.9000,Lower middle income
138,Philippines,PHL,23.790,37.0000,Lower middle income
139,Papua New Guinea,PNG,28.899,6.5000,Lower middle income
150,Sudan,SDN,33.477,22.7000,Lower middle income
151,Senegal,SEN,38.533,13.1000,Lower middle income
153,Solomon Islands,SLB,30.578,8.0000,Lower middle income
155,El Salvador,SLV,17.476,23.1093,Lower middle income
159,Sao Tome and Principe,STP,34.537,23.0000,Lower middle income
164,Swaziland,SWZ,30.093,24.7000,Lower middle income
166,Syrian Arab Republic,SYR,24.043,26.2000,Lower middle income
170,Tajikistan,TJK,30.792,16.0000,Lower middle income
172,Timor-Leste,TLS,35.755,1.1000,Lower middle income
179,Ukraine,UKR,11.100,41.0000,Lower middle income
182,Uzbekistan,UZB,22.500,38.2000,Lower middle income
186,Vietnam,VNM,15.537,43.9000,Lower middle income
187,Vanuatu,VUT,26.739,11.3000,Lower middle income
188,West Bank and Gaza,PSE,30.394,46.6000,Lower middle income
189,Samoa,WSM,26.172,15.3000,Lower middle income
190,"Yemen, Rep.",YEM,32.947,20.0000,Lower middle income
193,Zambia,ZMB,40.471,15.4000,Lower middle income

In [88]:
len(df[df.IncomeGroup == 'Lower middle income'])

50